//go:build darwin || dragonfly || freebsd || linux || nacl || netbsd || openbsd || solaris
// +build darwin dragonfly freebsd linux nacl netbsd openbsd solaris

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -objdir _obj -godefs rpc/constants_godef_unix.go

package rpc

const (
	max_path_size = 0x6a
)
